"""add_users_table_for_local_auth

Revision ID: 478d19b8b1ff
Revises: 60fb7ca540bf
Create Date: 2026-08-12 16:24:47.992935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '478d19b8b1ff'
down_revision: Union[str, None] = '60fb7ca540bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('picture', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_uid'), ['uid'], unique=True)

    with op.batch_alter_table('job_portals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_portals_portal_id'))
        batch_op.drop_index(batch_op.f('ix_job_portals_region'))

    op.drop_table('job_portals')
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_applications_listing_id'))
        batch_op.drop_index(batch_op.f('ix_job_applications_organization_id'))
        batch_op.drop_index(batch_op.f('ix_job_applications_project_id'))
        batch_op.drop_index(batch_op.f('ix_job_applications_resume_id'))

    op.drop_table('job_applications')
    with op.batch_alter_table('job_search_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_search_profiles_organization_id'))
        batch_op.drop_index(batch_op.f('ix_job_search_profiles_project_id'))

    op.drop_table('job_search_profiles')
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_listings_organization_id'))
        batch_op.drop_index(batch_op.f('ix_job_listings_portal_id'))
        batch_op.drop_index(batch_op.f('ix_job_listings_project_id'))
        batch_op.drop_index(batch_op.f('ix_job_listings_search_profile_id'))
        batch_op.drop_index(batch_op.f('ix_job_listings_status'))
        batch_op.drop_index(batch_op.f('ix_job_listings_url'))

    op.drop_table('job_listings')
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resumes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_resumes_project_id'))

    op.drop_table('resumes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('professional_title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('linkedin_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('github_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('portfolio_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('website_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('twitter_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('other_links', sqlite.JSON(), nullable=True),
    sa.Column('professional_summary', sqlite.JSON(), nullable=True),
    sa.Column('core_skills', sqlite.JSON(), nullable=True),
    sa.Column('work_experience', sqlite.JSON(), nullable=True),
    sa.Column('projects_section', sqlite.JSON(), nullable=True),
    sa.Column('education', sqlite.JSON(), nullable=True),
    sa.Column('certifications', sqlite.JSON(), nullable=True),
    sa.Column('awards', sqlite.JSON(), nullable=True),
    sa.Column('publications', sqlite.JSON(), nullable=True),
    sa.Column('volunteering', sqlite.JSON(), nullable=True),
    sa.Column('languages', sqlite.JSON(), nullable=True),
    sa.Column('custom_sections', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_resumes_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'project_id', name=op.f('uq_resumes_org_proj'))
    )
    with op.batch_alter_table('resumes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resumes_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_resumes_organization_id'), ['organization_id'], unique=False)

    op.create_table('job_listings',
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.Column('search_profile_id', sa.INTEGER(), nullable=True),
    sa.Column('portal_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('company', sa.VARCHAR(length=255), nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('url', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('source_portal', sa.VARCHAR(length=64), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('salary_range', sa.VARCHAR(length=255), nullable=True),
    sa.Column('posted_date', sa.VARCHAR(length=64), nullable=True),
    sa.Column('extracted_skills', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=64), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_job_listings_project_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_profile_id'], ['job_search_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_listings_url'), ['url'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_listings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_listings_search_profile_id'), ['search_profile_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_listings_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_listings_portal_id'), ['portal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_listings_organization_id'), ['organization_id'], unique=False)

    op.create_table('job_search_profiles',
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('keywords', sa.VARCHAR(length=255), nullable=False),
    sa.Column('location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('selected_portal_ids', sqlite.JSON(), nullable=True),
    sa.Column('remote_only', sa.BOOLEAN(), nullable=False),
    sa.Column('experience_level', sa.VARCHAR(length=64), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_job_search_profiles_project_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_search_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_search_profiles_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_search_profiles_organization_id'), ['organization_id'], unique=False)

    op.create_table('job_applications',
    sa.Column('organization_id', sa.INTEGER(), nullable=False),
    sa.Column('resume_id', sa.INTEGER(), nullable=False),
    sa.Column('job_title', sa.VARCHAR(length=255), nullable=True),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('job_description', sa.TEXT(), nullable=True),
    sa.Column('tailored_resume_json', sqlite.JSON(), nullable=True),
    sa.Column('cover_letter', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('agent_session_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=True),
    sa.Column('listing_id', sa.INTEGER(), nullable=True),
    sa.Column('application_method', sa.VARCHAR(length=64), server_default=sa.text("'MANUAL'"), nullable=False),
    sa.Column('submission_status', sa.VARCHAR(length=64), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['job_listings.id'], name=op.f('fk_job_applications_listing_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_job_applications_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_applications_resume_id'), ['resume_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_listing_id'), ['listing_id'], unique=False)

    op.create_table('job_portals',
    sa.Column('portal_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('region', sa.VARCHAR(length=64), nullable=False),
    sa.Column('access_method', sa.VARCHAR(length=64), nullable=False),
    sa.Column('base_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('requires_auth', sa.BOOLEAN(), nullable=False),
    sa.Column('extra_config', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_portals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_portals_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_portals_portal_id'), ['portal_id'], unique=1)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_uid'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
