"""add_usage_logs_and_organization_quotas

Revision ID: 60fb7ca540bf
Revises: b69ac38f9b68
Create Date: 2026-08-11 19:50:23.975883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60fb7ca540bf'
down_revision: Union[str, None] = 'b69ac38f9b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_usage_quotas',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('monthly_token_quota', sa.Integer(), nullable=False),
    sa.Column('monthly_budget_usd', sa.Float(), nullable=False),
    sa.Column('tokens_used_this_month', sa.Integer(), nullable=False),
    sa.Column('reserved_tokens_in_flight', sa.Integer(), nullable=False),
    sa.Column('cost_usd_this_month', sa.Float(), nullable=False),
    sa.Column('hard_limit_enabled', sa.Boolean(), nullable=False),
    sa.Column('alert_threshold_percentage', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organization_usage_quotas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_usage_quotas_organization_id'), ['organization_id'], unique=True)

    op.create_table('agent_usage_logs',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_uid', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('toon_tokens_saved', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('tool_calls_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_usage_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_usage_logs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_usage_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_usage_logs_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_usage_logs_user_uid'), ['user_uid'], unique=False)

    with op.batch_alter_table('agent_tool_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_agent_tool_runs_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_tool_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_foreign_key('fk_agent_tool_runs_agent_id', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_agent_tool_runs_organization_id', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')


def downgrade() -> None:
    with op.batch_alter_table('agent_tool_runs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agent_tool_runs_organization_id', type_='foreignkey')
        batch_op.drop_constraint('fk_agent_tool_runs_agent_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_agent_tool_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_agent_tool_runs_agent_id'))
        batch_op.drop_column('agent_id')
        batch_op.drop_column('organization_id')

    with op.batch_alter_table('agent_usage_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_usage_logs_user_uid'))
        batch_op.drop_index(batch_op.f('ix_agent_usage_logs_session_id'))
        batch_op.drop_index(batch_op.f('ix_agent_usage_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_agent_usage_logs_agent_id'))

    op.drop_table('agent_usage_logs')
    with op.batch_alter_table('organization_usage_quotas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_usage_quotas_organization_id'))

    op.drop_table('organization_usage_quotas')
