"""add memory pruning summarization and session summary columns

Revision ID: f6ede7af2312
Revises: 4d416d87fb32
Create Date: 2026-08-08 20:01:04.932242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6ede7af2312'
down_revision: Union[str, None] = '4d416d87fb32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_model_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('tool_pruning_turns', sa.Integer(), server_default='3', nullable=False))
        batch_op.add_column(sa.Column('summarization_threshold', sa.Integer(), server_default='10', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('summarization_threshold')
        batch_op.drop_column('tool_pruning_turns')
        batch_op.drop_column('summary_model_id')

    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.drop_column('summary')
    # ### end Alembic commands ###
