"""Generate shared TypeScript types from the FastAPI OpenAPI schema."""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from apps.api.main import create_app


OUT = ROOT / "packages/shared-types/src/generated/api.ts"


def ts_name(name: str) -> str:
    return name.replace("-", "_")


def ts_prop(name: str) -> str:
    if re.match(r"^[A-Za-z_$][A-Za-z0-9_$]*$", name):
        return name
    return repr(name)


def join_union(parts: list[str]) -> str:
    return " | ".join(dict.fromkeys(parts))


def render_schema(schema: dict[str, Any], schemas: dict[str, Any]) -> str:
    if "$ref" in schema:
        return ts_name(schema["$ref"].rsplit("/", 1)[-1])

    if "anyOf" in schema:
        return join_union([render_schema(part, schemas) for part in schema["anyOf"]])

    if "oneOf" in schema:
        return join_union([render_schema(part, schemas) for part in schema["oneOf"]])

    if "allOf" in schema:
        return " & ".join(render_schema(part, schemas) for part in schema["allOf"])

    if schema.get("enum"):
        return " | ".join(repr(value) for value in schema["enum"])

    schema_type = schema.get("type")
    schema_format = schema.get("format")

    if isinstance(schema_type, list):
        return join_union([render_schema({**schema, "type": item}, schemas) for item in schema_type])

    if schema_type == "null":
        return "null"
    if schema_format == "binary":
        return "Blob"
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "array":
        return f"{render_schema(schema.get('items', {}), schemas)}[]"
    if schema_type == "object" or "properties" in schema:
        additional = schema.get("additionalProperties")
        if additional and not schema.get("properties"):
            if additional is True:
                return "Record<string, unknown>"
            return f"Record<string, {render_schema(additional, schemas)}>"

        required = set(schema.get("required", []))
        lines = ["{"]
        for prop, prop_schema in schema.get("properties", {}).items():
            optional = "" if prop in required else "?"
            lines.append(f"  {ts_prop(prop)}{optional}: {render_schema(prop_schema, schemas)};")
        lines.append("}")
        return "\n".join(lines)

    return "unknown"


def main() -> None:
    openapi = create_app().openapi()
    schemas = openapi.get("components", {}).get("schemas", {})

    OUT.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "/* eslint-disable */",
        "// This file is generated by scripts/generate_openapi_types.py.",
        "// Do not edit by hand; update FastAPI schemas and run `pnpm typegen`.",
        "",
    ]

    for name in sorted(schemas):
        lines.append(f"export type {ts_name(name)} = {render_schema(schemas[name], schemas)};")
        lines.append("")

    OUT.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
